// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzSt5tk_R9Nn1yD3bwvLauDYKrw7v0qHQ',
    appId: '1:1040169351044:web:563b257998204dfb41cfd1',
    messagingSenderId: '1040169351044',
    projectId: 'car-app-ab21b',
    authDomain: 'car-app-ab21b.firebaseapp.com',
    storageBucket: 'car-app-ab21b.appspot.com',
    measurementId: 'G-PJEV0FDPJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL3V-u7mPFFcwc7T7JsUH5fp95p1Ey93M',
    appId: '1:1040169351044:android:2953280a3ee6812d41cfd1',
    messagingSenderId: '1040169351044',
    projectId: 'car-app-ab21b',
    storageBucket: 'car-app-ab21b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY04rlMO0Zf0ACC12WINK8W8I3pHr-A7k',
    appId: '1:1040169351044:ios:93972c26037ee27941cfd1',
    messagingSenderId: '1040169351044',
    projectId: 'car-app-ab21b',
    storageBucket: 'car-app-ab21b.appspot.com',
    iosBundleId: 'com.example.compareCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY04rlMO0Zf0ACC12WINK8W8I3pHr-A7k',
    appId: '1:1040169351044:ios:93972c26037ee27941cfd1',
    messagingSenderId: '1040169351044',
    projectId: 'car-app-ab21b',
    storageBucket: 'car-app-ab21b.appspot.com',
    iosBundleId: 'com.example.compareCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzSt5tk_R9Nn1yD3bwvLauDYKrw7v0qHQ',
    appId: '1:1040169351044:web:6682d185f11a923e41cfd1',
    messagingSenderId: '1040169351044',
    projectId: 'car-app-ab21b',
    authDomain: 'car-app-ab21b.firebaseapp.com',
    storageBucket: 'car-app-ab21b.appspot.com',
    measurementId: 'G-G9VLQ50G0Z',
  );

}